version: '3'
services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: shopping
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345678
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        env_file:
            - .env